Associations
deyemiobaa/oop-school-library pull request #3
Opened 2022-06-24 20:50 UTC by deyemiobaa

### Setup OOP Associations

- create has-many relationships between the classroom and students
- create a belongs-to relationship between the student and classrooms
- create has-many relationships between the person and rentals
- create a belongs-to relationship between the rentals and the person
- create has-many relationships between the books and rentals
- create a belongs-to relationship between the rentals and books

2022-06-24 21:06 UTC, mikethreels requested changes
Hi Sodiq, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 21:06 UTC, mikethreels commented on student.rb
> +    classroom.add_student(self) unless classroom.students.include?(self)
- [ ] in this line you are calling the `add_student` method from Classroom however, this is not how you're intended to set up the belongs-to side please have another look at [this artilce](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships).

2022-06-24 21:06 UTC, mikethreels commented on book.rb
> +    @rentals << rental
- [ ] the method for adding rentals should look a little different, please have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) for more details.

2022-06-24 21:06 UTC, mikethreels commented on rental.rb
> +  end
- [ ] in this case you don't create methods for this relationship. The constructor of Rental should be modified so Book and Person are set in it to break the many-to-many relationship, please have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) for more details

2022-06-24 21:06 UTC, mikethreels commented on person.rb
> +  end
- [ ] the method for achieving the has-many relationship should look a little different, please have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) for more details.

2022-06-24 21:06 UTC, mikethreels commented on person.rb
> +    @books_rented = []
- [ ] `@rentals` or in this case `@books_rented` should be added to the attribute_accessor.

2022-06-24 22:46 UTC, medaminedev66 requested changes
Hi @deyemiobaa 😃,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 22:46 UTC, medaminedev66 commented on person.rb
- [ ] A person has many rentals (the has-many side of Person and Rental) and that means you should add a method for adding rentals to the Person class. Check out the example in this lesson: [link](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship
) for more information.

2022-06-24 22:46 UTC, medaminedev66 commented on rental.rb
> +  attr_reader :book, :person
- [ ] A rental belongs to a book and also belongs to a person. To make this relationship possible we need to add an attr_accessor for @book and @person in the Rental class.

2022-06-24 22:46 UTC, medaminedev66 commented on book.rb
> +  end
- [ ] A book has many rentals which means that a method for adding rentals should be present in the Book class. You can check out the example in a previous lesson for more information: [link](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship)

2022-06-24 22:46 UTC, medaminedev66 commented on student.rb
> +    classroom.add_student(self) unless classroom.students.include?(self)
- [ ] As requested by the previous reviewer, you still need to set up the belongs-to side (a student belongs to a classroom) correctly as it's shown in [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships).

2022-06-25 00:57 UTC, Kingstalux approved these changes
Hi @deyemiobaa, 
# Status: Approved ✔️ ✔️ ✔️ 
![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/85113567/175752089-6700bcf4-ebbe-4f37-9cee-45e7611089a3.gif)

Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-25 00:57 UTC, Kingstalux commented on student.rb
> +  attr_accessor :classroom
- [ ] (OPTIONAL) Classroom should remain an `attr_reader` since we have a method dedicated to adding new classrooms 👍

2022-06-25 00:57 UTC, Kingstalux commented on student.rb
> +    classroom.students << self unless classroom.students.include?(self)
- [ ] (OPTIONAL) The student should be added to the classroom like this 👍 `classroom.students.push(self) unless classroom.students.include?(self)` Kindly correct this 💯

2022-06-25 01:03 UTC, closed without merging